/// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar pour les principes actifs
  principesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'principes', // Dossier: docs/principes/
    },
  ],

  // Sidebar pour les produits analysés
  produitsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'produits', // Dossier: docs/produits/
    },
  ],
};

export default sidebars;
