name: Check build on Pull Requests

on:
  pull_request:
    branches: [ sources ]

jobs:
  build:
    runs-on: ubuntu-latest
    env :
      NEXT_PUBLIC_SUPABASE_URL=https://jrbaeawbpehqdqsecjon.supabase.co
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=sb_publishable_-ZJncsrA372wYMxrBsjWVA_leUtxV-8
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install
      - run: npm run build
